//! The events the application ships with.
//!
//! Thirty-six events, in Ukrainian and English, covering environment, combat, weather,
//! creatures, magic and items.
//!
//! These are a starting point, not a fixed set — the editor can change all of it, and
//! anything a person edits stops being overwritten from here.
//!
//! # Writing a term list
//!
//! Coverage is the entire job. A verb the narrator says and this file does not list is a
//! sound that never plays, and there is no feedback at the table telling anyone why. So
//! each list aims to hold *every* ordinary way its event gets described — and nothing
//! that describes something else.
//!
//! Two rules make that tractable:
//!
//! * **List lexemes, not inflections.** The stemmer strips endings, so `гарчить` covers
//!   `гарчиш`, `гарчимо`, `гарчите`. It cannot cover `загарчав`: Ukrainian aspect and
//!   prefixes change the stem itself, so every prefixed and perfective form is its own
//!   entry. This is why the lists look repetitive — `відчиняє`, `прочиняє`, `розчиняє`,
//!   `відкриває` are four different words to a stemmer, and all four get said.
//! * **Never share a verb between events whose objects can co-occur.** `б'є` belongs to
//!   the sword, not to breaking glass, because "б'є мечем по склу" must not be ambiguous.
//!   Where two events do share a verb — `вдарила` for both lightning and a sword — the
//!   keyword tells them apart, and the action gate needs both to fire.

use crate::event::{terms, EventDefinition, Lang, Phrase, Term};

pub fn seed_events() -> Vec<EventDefinition> {
    vec![
        open_door(),
        door_slam(),
        chest_open(),
        sword_swing(),
        bow_shot(),
        thunder(),
        fire(),
        water_splash(),
        wolf_growl(),
        small_creature_scurry(),
        footsteps(),
        magic_cast(),
        coins(),
        glass_shatter(),
        fireball(),
        spell_heal(),
        spell_teleport(),
        spell_ice(),
        sword_unsheathe(),
        shield_block(),
        armor_clank(),
        body_fall(),
        scream(),
        dragon_roar(),
        horse(),
        ghost_moan(),
        bones(),
        crow(),
        potion_drink(),
        dice_roll(),
        keys_lock(),
        scroll_paper(),
        wind(),
        rain(),
        bell(),
        tavern(),
    ]
}

/// Phrases in one call, since every event needs the same two kinds.
fn phrases(examples_en: &[&str], examples_uk: &[&str], commands: &[&str]) -> Vec<Phrase> {
    examples_en
        .iter()
        .map(|t| Phrase::example(Lang::En, t))
        .chain(examples_uk.iter().map(|t| Phrase::example(Lang::Uk, t)))
        .chain(commands.iter().map(|t| Phrase::command(t)))
        .collect()
}

fn open_door() -> EventDefinition {
    EventDefinition {
        category: "environment".to_string(),
        ..EventDefinition::new("OPEN_DOOR", "Open Door")
    }
    .with_phrases(phrases(
        &[
            "opens the door",
            "pushes the door open",
            "push open the door",
            "the door slowly opens",
            "the door swings open",
            "you open the door",
            "eases the door open",
            "throws the door open",
            "the door creaks open",
            "unlatches the door and steps through",
            "pulls the gate open",
        ],
        &[
            "відчиняє двері",
            "відчиняєте двері",
            "відкриває двері",
            "двері повільно відчиняються",
            "двері зі скрипом відчиняються",
            "прочиняє двері",
            "розчахує двері навстіж",
            "штовхає двері й вони піддаються",
            "відчиняє браму",
            "ти відкриваєш двері до зали",
        ],
        &["sound door", "trigger door"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "door",
            "doors",
            "doorway",
            "gate",
            "gates",
            "hatch",
            "portal",
            "двері",
            "дверей",
            "дверима",
            "дверцята",
            "брама",
            "браму",
            "брами",
            "ворота",
            "воріт",
            "хвіртка",
            "хвіртку",
            "люк",
            "хвіртці",
            "хвірткою",
            "люком",
            "люків",
        ]),
        Term::actions(&[
            // English
            "open",
            "opens",
            "opening",
            "opened",
            "push",
            "pushes",
            "pushed",
            "swings open",
            "creaks open",
            "eases open",
            "throws open",
            "pulls open",
            "unlatches",
            "unbolts",
            "unlocks",
            "shoves",
            // Ukrainian: one entry per prefix and aspect, because the stemmer only
            // strips endings.
            "відчиняє",
            "відчиняєте",
            "відчинив",
            "відчинила",
            "відчинили",
            "відчиняти",
            "відчиняються",
            "прочиняє",
            "прочинив",
            "прочинили",
            "розчиняє",
            "розчинив",
            "розчахує",
            "розчахнув",
            "розчахнулися",
            "відкриває",
            "відкрив",
            "відкрила",
            "відкрили",
            "відкривати",
            "відхиляє",
            "відхилив",
            "привідкрив",
            "штовхає",
            "штовхнув",
            "штовхнула",
            "піддалися",
            "рипнули",
            "заскрипіли",
        ]),
        Term::negatives(&[
            "painted door",
            "drawing of a door",
            "the door is locked",
            "door is shut",
            "намальовані двері",
            "намальований на дверях",
            "двері зачинені",
            "двері замкнені",
            "двері не піддаються",
        ]),
    ]))
    .with_cooldown(2_500)
}

fn door_slam() -> EventDefinition {
    EventDefinition {
        category: "environment".to_string(),
        ..EventDefinition::new("DOOR_SLAM", "Door Slam")
    }
    .with_phrases(phrases(
        &[
            "slams the door",
            "the door slams shut",
            "closes the door behind you",
            "the door swings shut",
            "bangs the door closed",
            "the gate crashes shut behind you",
        ],
        &[
            "грюкає дверима",
            "двері гримнули",
            "зачиняє двері",
            "двері з грюкотом зачиняються",
            "захлопує двері за собою",
            "брама з гуркотом зачиняється",
        ],
        &["sound slam", "trigger slam"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "door",
            "doors",
            "gate",
            "gates",
            "hatch",
            "двері",
            "дверей",
            "дверима",
            "дверцята",
            "брама",
            "браму",
            "брами",
            "ворота",
            "воріт",
            "хвіртка",
            "хвіртку",
            "люк",
            "хвіртці",
            "хвірткою",
            "люком",
            "люків",
        ]),
        Term::actions(&[
            "slams",
            "slam",
            "slammed",
            "shuts",
            "shut",
            "closes",
            "close",
            "closed",
            "bangs",
            "banged",
            "swings shut",
            "crashes shut",
            "snaps shut",
            "зачиняє",
            "зачинив",
            "зачинила",
            "зачинили",
            "зачиняються",
            "причиняє",
            "причинив",
            "захлопує",
            "захлопнув",
            "захлопнула",
            "захряснув",
            "грюкає",
            "грюкнув",
            "грюкнули",
            "грюкотом",
            "гримнув",
            "гримнули",
            "хряснув",
            "хряснули",
            "затраснув",
            "гуркотом",
        ]),
        Term::negatives(&["painted door", "намальовані двері", "двері вже зачинені"]),
    ]))
    .with_cooldown(2_500)
}

fn chest_open() -> EventDefinition {
    EventDefinition {
        category: "environment".to_string(),
        ..EventDefinition::new("CHEST_OPEN", "Chest Open")
    }
    .with_phrases(phrases(
        &[
            "opens the chest",
            "lifts the lid of the chest",
            "the chest creaks open",
            "pries the chest open",
            "unlocks the chest and lifts the lid",
            "throws open the crate",
        ],
        &[
            "відчиняє скриню",
            "відкриває скриню",
            "піднімає кришку скрині",
            "скриня зі скрипом відчиняється",
            "ти відкриваєш скриню",
            "зриває замок і відкриває скриню",
        ],
        &["sound chest", "trigger chest"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "chest",
            "chests",
            "coffer",
            "casket",
            "crate",
            "lid",
            "strongbox",
            "скриня",
            "скриню",
            "скрині",
            "скринька",
            "скриньку",
            "сундук",
            "сундука",
            "ящик",
            "ящика",
            "шухляда",
            "шухляду",
            "кришка",
            "кришку",
            "скриньці",
            "скринькою",
            "кришці",
            "кришкою",
        ]),
        Term::actions(&[
            "open",
            "opens",
            "opening",
            "opened",
            "lifts",
            "lift",
            "pries",
            "prises",
            "unlocks",
            "unlatches",
            "creaks open",
            "throws open",
            "forces open",
            "відчиняє",
            "відчинив",
            "відчиняєш",
            "відкриває",
            "відкрив",
            "відкриваєш",
            "піднімає",
            "підняв",
            "відмикає",
            "відімкнув",
            "зриває",
            "зірвав",
            "відкидає",
            "відкинув",
            "зламує",
            "зламав",
            "розкриває",
            "розкрив",
        ]),
        Term::negatives(&[
            // "chest" is a body part, and combat narration is full of it.
            "in the chest",
            "his chest",
            "her chest",
            "your chest",
            "chest wound",
            "clutches his chest",
            "в груди",
            "у груди",
            "рана в грудях",
        ]),
    ]))
    .with_cooldown(4_000)
}

fn sword_swing() -> EventDefinition {
    EventDefinition {
        category: "combat".to_string(),
        ..EventDefinition::new("SWORD_SWING", "Sword Swing")
    }
    .with_phrases(phrases(
        &[
            "swings his sword",
            "swings her sword",
            "swings at you",
            "slashes at you with his sword",
            "strikes with his blade",
            "attacks you with a sword",
            "brings the sword down on you",
            "draws his blade and lunges",
            "the blade whistles past your ear",
        ],
        &[
            "б'є мечем",
            "замахується мечем",
            "рубає мечем",
            "атакує тебе мечем",
            "вдарив мечем",
            "розмахнувся мечем",
            "меч здіймається над його головою",
            "вихоплює меч і кидається на тебе",
            "опускає клинок на твій щит",
        ],
        &["sound sword", "trigger sword"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "sword",
            "swords",
            "blade",
            "blades",
            "katana",
            "sabre",
            "saber",
            "longsword",
            "greatsword",
            "scimitar",
            "меч",
            "меча",
            "мечем",
            "мечі",
            "мечів",
            "клинок",
            "клинка",
            "клинком",
            "лезо",
            "лезом",
            "шабля",
            "шаблю",
            "шаблею",
            "катана",
            "катаною",
            "мечами",
            "шабель",
        ]),
        Term::actions(&[
            "swings",
            "swing",
            "swung",
            "slashes",
            "slash",
            "strikes",
            "strike",
            "attacks",
            "attack",
            "lunges",
            "lunge",
            "stabs",
            "thrusts",
            "hacks",
            "cleaves",
            "parries",
            "draws",
            "unsheathes",
            "brings down",
            "whistles past",
            "б'є",
            "бє",
            "бив",
            "б'ють",
            "вдарив",
            "вдарила",
            "вдаряє",
            "ударив",
            "рубає",
            "рубонув",
            "рубанув",
            "рубнув",
            "січе",
            "посік",
            "махає",
            "махнув",
            "змахнув",
            "замахується",
            "замахнувся",
            "замахнулася",
            "розмахується",
            "розмахнувся",
            "заносить",
            "заніс",
            "опускає",
            "опустив",
            "здіймає",
            "здійняв",
            "здіймається",
            "встромив",
            "встромляє",
            "простромив",
            "настромив",
            "штрикає",
            "штрикнув",
            "коле",
            "кольнув",
            "пронизує",
            "пронизав",
            "атакує",
            "атакував",
            "нападає",
            "напав",
            "кидається",
            "вихоплює",
            "вихопив",
            "витягує",
            "витягнув",
            "дістає",
            "дістав",
            "виймає",
            "вийняв",
            "оголює",
            "оголив",
        ]),
        Term::negatives(&[
            "lying on the table",
            "hangs on the wall",
            "hanging on the wall",
            "sheathed at his hip",
            "on his belt",
            "лежить на столі",
            "висить на стіні",
            "у піхвах",
            "на поясі",
            // Drawing a blade is its own event, and both share `вихоплює`. Without
            // these, "вихопив шаблю з піхов" scored identically for a swing and a draw.
            "з піхов",
            "із піхов",
            "from its scabbard",
            "out of its sheath",
        ]),
    ]))
    .with_cooldown(1_500)
}

fn bow_shot() -> EventDefinition {
    EventDefinition {
        category: "combat".to_string(),
        ..EventDefinition::new("BOW_SHOT", "Bow Shot")
    }
    .with_phrases(phrases(
        &[
            "looses an arrow",
            "fires an arrow at you",
            "draws his bow and shoots",
            "an arrow whistles past",
            "the arrow buries itself in the wood",
            "nocks an arrow and releases",
        ],
        &[
            "пускає стрілу",
            "стріляє з лука",
            "випускає стрілу",
            "стріла свистить повз",
            "стріла влучає йому в груди",
            "натягує тятиву і стріляє",
        ],
        &["sound arrow", "trigger bow"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "arrow",
            "arrows",
            "bow",
            "bows",
            "crossbow",
            "bolt",
            "bolts",
            "quiver",
            "стріла",
            "стрілу",
            "стріли",
            "стрілою",
            "стріл",
            "лук",
            "лука",
            "луком",
            "арбалет",
            "арбалета",
            "болт",
            "болтом",
            "тятива",
            "тятиву",
            "сагайдак",
            "луків",
            "сагайдака",
            "сагайдаку",
        ]),
        Term::actions(&[
            "looses",
            "loose",
            "fires",
            "fire",
            "shoots",
            "shoot",
            "nocks",
            "releases",
            "draws",
            "whistles",
            "buries",
            "strikes",
            "hits",
            "flies past",
            "sails past",
            "пускає",
            "пустив",
            "пустила",
            "стріляє",
            "вистрілив",
            "стрельнув",
            "випускає",
            "випустив",
            "натягує",
            "натягнув",
            "спускає",
            "спустив",
            "пролітає",
            "пролетів",
            "пролетіла",
            "просвистів",
            "просвистіла",
            "свистить",
            "свиснула",
            "шугнула",
            "влучає",
            "влучила",
            "поцілив",
            "прошила",
            "встромилася",
            "вражає",
            "вразив",
            "вп'ялася",
            "впилася",
        ]),
        Term::negatives(&[
            // "bows" the gesture stems to the same word as the weapon.
            "bows to",
            "takes a bow",
            "bows before",
            "bows deeply",
            "вклоняється",
            "вклонився",
            "робить уклін",
            // An arrow that is stopped belongs to the shield, not to the bow: the sound
            // wanted is the impact on the shield, and the shot has already happened.
            "deflects the arrow",
            "blocks the arrow",
            "catches the arrow",
            "відбив стрілу",
            "відбиває стрілу",
            "заблокував стрілу",
            "спіймав стрілу",
        ]),
    ]))
    .with_cooldown(1_500)
}

fn thunder() -> EventDefinition {
    EventDefinition {
        category: "weather".to_string(),
        ..EventDefinition::new("THUNDER", "Thunder")
    }
    .with_phrases(phrases(
        &[
            "thunder rolls",
            "thunder crashes",
            "a peal of thunder",
            "lightning splits the sky",
            "thunder rumbles over the hills",
            "lightning flashes above the castle",
        ],
        &[
            "гримить грім",
            "лунає грім",
            "блискавка розтинає небо",
            "спалахнула блискавка",
            "прогримів грім над замком",
            "небо розколює блискавка",
        ],
        &["sound thunder", "trigger thunder"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "thunder",
            "thunderclap",
            "lightning",
            "storm",
            "tempest",
            "грім",
            "грому",
            "громом",
            "блискавка",
            "блискавку",
            "блискавиця",
            "гроза",
            "грози",
            "буря",
            "бурю",
            "блискавці",
            "блискавкою",
            "бурею",
        ]),
        Term::actions(&[
            "rolls",
            "roll",
            "crashes",
            "crash",
            "rumbles",
            "rumble",
            "booms",
            "splits",
            "flashes",
            "cracks",
            "peals",
            "strikes",
            "breaks over",
            "гримить",
            "гримнув",
            "загримів",
            "прогримів",
            "гуркоче",
            "загуркотів",
            "лунає",
            "пролунав",
            "розтинає",
            "розітнула",
            "розколює",
            "розколола",
            "спалахує",
            "спалахнула",
            "спалахнуло",
            "блиснула",
            "блиснуло",
            "вдарила",
            "вдарив",
            "гуде",
            "загуло",
            "торохнув",
            "розкотився",
            "прокотився",
            "прокотилася",
            "загуркотіла",
            "загримотіло",
            "розколовся",
            "спалахнув",
            "блиснув",
            "гримнула",
        ]),
        Term::negatives(&[
            "sound of thunder in the distance yesterday",
            "як грім серед ясного неба",
        ]),
    ]))
    // Loud and unmissable, so it is held to a stricter standard than a door.
    .with_threshold(0.85)
    .with_cooldown(6_000)
}

fn fire() -> EventDefinition {
    EventDefinition {
        category: "environment".to_string(),
        ..EventDefinition::new("FIRE", "Fire")
    }
    .with_phrases(phrases(
        &[
            "bursts into flames",
            "the fire flares up",
            "catches fire",
            "lights the torch",
            "the oil ignites with a roar",
            "the campfire crackles to life",
        ],
        &[
            "спалахує вогонь",
            "спалахує полум'я",
            "загоряється",
            "запалює факел",
            "факел загорівся",
            "багаття розгорається",
        ],
        &["sound fire", "trigger fire"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "fire",
            "flame",
            "flames",
            "torch",
            "torches",
            "campfire",
            "bonfire",
            "blaze",
            "brazier",
            "вогонь",
            "вогню",
            "вогнем",
            "полум'я",
            "полум'ям",
            "факел",
            "факела",
            "факелом",
            "смолоскип",
            "смолоскипа",
            "багаття",
            "ватра",
            "вогнище",
            "жар",
            "іскра",
            "іскри",
            "жаром",
        ]),
        Term::actions(&[
            "bursts",
            "burst",
            "flares",
            "flare",
            "catches",
            "ignites",
            "ignite",
            "lights",
            "light",
            "lit",
            "erupts",
            "crackles",
            "roars up",
            "blazes",
            "спалахує",
            "спалахнув",
            "спалахнуло",
            "спалахнула",
            "загоряється",
            "загорівся",
            "загорілася",
            "загорілося",
            "займається",
            "зайнявся",
            "палає",
            "запалав",
            "запалює",
            "запалив",
            "підпалює",
            "підпалив",
            "розгорається",
            "розгорівся",
            "спалює",
            "спопелив",
            "тріщить",
            "палахкотить",
            "жевріє",
            "зайнялося",
            "зайнялась",
            "зайнялася",
            "шугнуло",
            "шугнула",
            "шугнув",
            "спалахнула",
            "розгорілося",
        ]),
        Term::negatives(&[
            "cease fire",
            "under fire",
            "fired from",
            "fire resistance",
            "стійкість до вогню",
            "опір вогню",
            "вогнетривкий",
        ]),
    ]))
    .with_cooldown(4_000)
}

fn water_splash() -> EventDefinition {
    EventDefinition {
        category: "environment".to_string(),
        ..EventDefinition::new("WATER_SPLASH", "Water Splash")
    }
    .with_phrases(phrases(
        &[
            "falls into the water",
            "dives into the water",
            "with a loud splash",
            "splashes into the river",
            "plunges into the lake",
            "wades into the stream",
        ],
        &[
            "падає у воду",
            "стрибає у воду",
            "з гучним плескотом",
            "шубовснув у річку",
            "пірнув у річку",
            "занурюється у воду",
        ],
        &["sound splash", "trigger water"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "water",
            "splash",
            "river",
            "lake",
            "pond",
            "stream",
            "canal",
            "moat",
            "вода",
            "воду",
            "води",
            "водою",
            "річка",
            "річку",
            "річці",
            "озеро",
            "озера",
            "ставок",
            "потік",
            "струмок",
            "рів",
            "плескіт",
            "хвиля",
            "хвилі",
            "хвилю",
            "хвилею",
            "калюжа",
            "калюжі",
            "калюжу",
            "калюжею",
        ]),
        Term::actions(&[
            "falls",
            "fall",
            "fell",
            "dives",
            "dive",
            "dove",
            "splashes",
            "splash",
            "plunges",
            "jumps",
            "leaps",
            "wades",
            "sinks",
            "topples",
            "падає",
            "впав",
            "впала",
            "впало",
            "стрибає",
            "стрибнув",
            "стрибнула",
            "пірнає",
            "пірнув",
            "пірнула",
            "шубовснув",
            "плюхнувся",
            "плюхнув",
            "занурюється",
            "занурився",
            "бовтнув",
            "хлюпає",
            "хлюпнув",
            "плескає",
            "плеснув",
            "бризкає",
            "розбризкує",
            "зісковзнув",
        ]),
        Term::negatives(&[
            // Said at a real table: "ходить по воді і п'є воду". Neither is a splash.
            "п'є воду",
            "п'ють воду",
            "drinks water",
            "glass of water",
            "склянку води",
            "чашку води",
            "по воді",
            "walks on water",
        ]),
    ]))
    .with_cooldown(3_000)
}

fn wolf_growl() -> EventDefinition {
    EventDefinition {
        category: "creatures".to_string(),
        ..EventDefinition::new("WOLF_GROWL", "Wolf Growl")
    }
    .with_phrases(phrases(
        &[
            "the wolf growls",
            "wolves growl in the dark",
            "a wolf snarls at you",
            "a wolf howls somewhere beyond the hill",
            "the beast bares its teeth",
        ],
        &[
            "вовк гарчить",
            "вовки гарчать",
            "вовк загарчав із кущів",
            "вовки завили десь за пагорбом",
            "в темному лісі вовк виє",
        ],
        &["sound wolf", "trigger wolf"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "wolf",
            "wolves",
            "beast",
            "beasts",
            "hound",
            "hounds",
            "warg",
            "вовк",
            "вовка",
            "вовки",
            "вовків",
            "вовчиця",
            "звір",
            "звіра",
            "звірі",
            "пес",
            "пса",
            "хижак",
            "псу",
            "псом",
            "пси",
            "псів",
        ]),
        Term::actions(&[
            "growls",
            "growl",
            "growled",
            "snarls",
            "snarl",
            "howls",
            "howl",
            "howled",
            "bares",
            "barks",
            "yelps",
            "snaps",
            "гарчить",
            "гарчав",
            "гарчали",
            "гарчать",
            "загарчав",
            "загарчала",
            "виє",
            "вив",
            "виють",
            "завив",
            "завила",
            "завили",
            "завиває",
            "завивають",
            "гавкає",
            "гавкнув",
            "рикає",
            "рикнув",
            "ричить",
            "вишкіряє",
            "вискалює",
            "шкірить",
            "загрозливо",
        ]),
        Term::negatives(&[
            "painted wolf",
            "wolf pelt",
            "wolf on the banner",
            "намальований вовк",
            "на дверях намальований",
            "вовча шкура",
            "герб з вовком",
        ]),
    ]))
    .with_cooldown(4_000)
}

/// The event that keyword matching alone cannot do.
///
/// "Something small suddenly runs between your feet" contains neither "rat" nor "mouse".
/// Layers 1–3 cover the phrasings we can think of; the semantic layer generalises to the
/// ones we cannot.
fn small_creature_scurry() -> EventDefinition {
    EventDefinition {
        category: "creatures".to_string(),
        ..EventDefinition::new("SMALL_CREATURE_SCURRY", "Small Creature Scurry")
    }
    .with_phrases(phrases(
        &[
            "something small runs across the floor",
            "something small runs between your feet",
            "a tiny creature scurries past",
            "a rat scurries away",
            "something tiny darts between your legs",
            "you hear scratching in the walls",
        ],
        &[
            "щось маленьке пробігає між ногами",
            "щур пробігає повз",
            "маленька істота шмигає у темряві",
            "щось дрібне метнулось під ноги",
            "маленький щур пробігає",
            "у стінах шкребеться щось дрібне",
        ],
        &["sound rat", "trigger rat"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "rat",
            "rats",
            "mouse",
            "mice",
            "rodent",
            "creature",
            "critter",
            "vermin",
            "щур",
            "щура",
            "щури",
            "щурів",
            "пацюк",
            "пацюка",
            "миша",
            "мишу",
            "миші",
            "істота",
            "істоти",
            "тварина",
            "тваринка",
            "щуром",
            "мишею",
            "мишей",
        ]),
        Term::actions(&[
            "scurries",
            "scurry",
            "darts",
            "dart",
            "runs",
            "run",
            "ran",
            "scampers",
            "scratches",
            "scuttles",
            "squeaks",
            "skitters",
            "пробігає",
            "пробіг",
            "пробігла",
            "пробігли",
            "шмигає",
            "шмигнув",
            "прошмигнув",
            "майнув",
            "промайнуло",
            "метнувся",
            "метнулось",
            "метнулося",
            "шурхотить",
            "зашурхотіло",
            "шкребе",
            "шкребеться",
            "шкрябає",
            "дряпає",
            "писнув",
            "пискнув",
            "прошмигнула",
            "метнулася",
            "метнулись",
            "шаснув",
            "шаснула",
            "дряпнув",
        ]),
        Term::negatives(&[]),
    ]))
    .with_cooldown(5_000)
}

fn footsteps() -> EventDefinition {
    EventDefinition {
        category: "environment".to_string(),
        ..EventDefinition::new("FOOTSTEPS", "Footsteps")
    }
    .with_phrases(phrases(
        &[
            "you hear footsteps",
            "footsteps echo down the corridor",
            "footsteps approach",
            "the sound of footsteps",
            "heavy boots on the stone floor",
        ],
        &[
            "ви чуєте кроки",
            "лунають кроки",
            "кроки наближаються",
            "чути важкі кроки",
            "почулися кроки за дверима",
        ],
        &["sound footsteps", "trigger steps"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "footsteps",
            "footfall",
            "boots",
            "кроки",
            "кроків",
            "кроками",
            "хода",
            "тупіт",
            "чоботи",
            "чобіт",
        ]),
        Term::actions(&[
            "hear",
            "hears",
            "heard",
            "echo",
            "echoes",
            "approach",
            "approaches",
            "approaching",
            "sound of",
            "ring out",
            "draw closer",
            "чуєте",
            "чуєш",
            "чути",
            "чув",
            "чула",
            "почув",
            "почулися",
            "почулись",
            "лунають",
            "лунає",
            "пролунали",
            "наближаються",
            "наблизилися",
            "відлунюють",
            "тупотять",
            "затупотіли",
            "крокує",
            "ступає",
            "ступив",
            "шаркає",
            "долинають",
        ]),
        Term::negatives(&[
            // "кроки" measures distance as often as it means walking.
            "кроків від",
            "кілька кроків",
            "за кроків",
            "на відстані",
            "steps away",
            "a few steps",
            "paces away",
            "next steps",
        ]),
    ]))
    .with_cooldown(5_000)
}

fn magic_cast() -> EventDefinition {
    EventDefinition {
        category: "magic".to_string(),
        ..EventDefinition::new("MAGIC_CAST", "Magic Cast")
    }
    .with_phrases(phrases(
        &[
            "casts a spell",
            "the spell takes effect",
            "chants an incantation",
            "unleashes a bolt of magic",
            "weaves the last gesture and the spell lands",
        ],
        &[
            "читає заклинання",
            "промовляє заклинання",
            "кастує заклинання",
            "заклинання спрацьовує",
            "чаклун творить чари",
        ],
        &["sound magic", "trigger spell"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "spell",
            "spells",
            "incantation",
            "magic",
            "cantrip",
            "enchantment",
            "заклинання",
            "закляття",
            "чари",
            "чару",
            "чарів",
            "магія",
            "магії",
            "магією",
            "чаклунство",
            "заклятт",
            // Whisper writes the Russian spelling often enough to matter, and the word
            // means the same thing.
            "чары",
            "заклинань",
            "чарами",
        ]),
        Term::actions(&[
            "casts",
            "cast",
            "casting",
            "chants",
            "chant",
            "unleashes",
            "weaves",
            "takes effect",
            "invokes",
            "conjures",
            "utters",
            "channels",
            "читає",
            "прочитав",
            "промовляє",
            "промовив",
            "вимовляє",
            "вимовив",
            "кастує",
            "скастував",
            "творить",
            "сотворив",
            "чаклує",
            "начаклував",
            "накладає",
            "наклав",
            "застосовує",
            "застосував",
            "шепоче",
            "прошепотів",
            "викликає",
            "викликав",
            "спрацьовує",
            "спрацювало",
            "спрацювали",
            "активує",
            "плете",
            "сплітає",
            "закликає",
            "закликав",
        ]),
        Term::negatives(&[
            "spellbook",
            "book of spells",
            "spell slot",
            "spell list",
            "книга заклинань",
            "школа магії",
            "список заклинань",
            "комірка заклинань",
            // A named kind of magic belongs to its own event. Without these, "читає
            // заклинання зцілення" plays a generic shimmer over the healing sound.
            "fireball",
            "cure wounds",
            "teleport",
            "ray of frost",
            "вогняна куля",
            "вогняну кулю",
            "фаєрбол",
            "зцілення",
            "телепорт",
            "крижаний промінь",
        ]),
    ]))
    .with_cooldown(2_500)
}

fn coins() -> EventDefinition {
    EventDefinition {
        category: "items".to_string(),
        ..EventDefinition::new("COINS", "Coins")
    }
    .with_phrases(phrases(
        &[
            "tosses a coin",
            "coins spill across the floor",
            "drops a bag of coins",
            "counts out the gold coins",
            "the purse lands on the table with a clink",
        ],
        &[
            "кидає монету",
            "монети розсипаються",
            "висипає монети",
            "брязкіт монет",
            "рахує монети",
        ],
        &["sound coins", "trigger gold"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "coin",
            "coins",
            "gold",
            "silver",
            "money",
            "purse",
            "pouch",
            "монета",
            "монету",
            "монети",
            "монет",
            "монетами",
            "золото",
            "золота",
            "золотом",
            "гроші",
            "грошей",
            "срібло",
            "срібла",
            "дукати",
            "гаманець",
            "сріблом",
            "гаманця",
            "гаманцем",
        ]),
        Term::actions(&[
            "tosses",
            "toss",
            "drops",
            "drop",
            "spill",
            "spills",
            "counts",
            "count",
            "jingle",
            "jingles",
            "clink",
            "clinks",
            "scatter",
            "hands over",
            "pays",
            "кидає",
            "кинув",
            "кинула",
            "розсипаються",
            "розсипались",
            "розсипалися",
            "висипає",
            "висипав",
            "дзвенять",
            "задзвеніли",
            "брязкають",
            "брязнули",
            "брязкіт",
            "падають",
            "впали",
            "рахує",
            "порахував",
            "платить",
            "заплатив",
            "простягає",
            "віддає",
            "сипле",
            "висипався",
            "покотилися",
            "дзвякнули",
            "брязнув",
        ]),
        Term::negatives(&[]),
    ]))
    .with_cooldown(3_000)
}

fn glass_shatter() -> EventDefinition {
    EventDefinition {
        category: "environment".to_string(),
        ..EventDefinition::new("GLASS_SHATTER", "Glass Shatter")
    }
    .with_phrases(phrases(
        &[
            "the glass shatters",
            "the window breaks",
            "smashes the bottle",
            "glass shatters across the floor",
            "the mirror cracks and falls apart",
        ],
        &[
            "скло розбивається",
            "вікно розлітається на друзки",
            "розбиває пляшку",
            "дзвін розбитого скла",
            "пляшка розбилась об стіл",
        ],
        &["sound glass", "trigger glass"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "glass",
            "window",
            "windows",
            "bottle",
            "bottles",
            "mirror",
            "pane",
            "скло",
            "скла",
            "склом",
            "вікно",
            "вікна",
            "шибка",
            "шибку",
            "пляшка",
            "пляшку",
            "пляшки",
            "дзеркало",
            "дзеркала",
            "келих",
            "друзки",
            "пляшці",
            "пляшкою",
            "пляшок",
            "дзеркалом",
            "шибці",
            "ваза",
            "вази",
            "вазу",
            "вазою",
        ]),
        Term::actions(&[
            "shatters",
            "shatter",
            "shattered",
            "breaks",
            "break",
            "broke",
            "smashes",
            "smash",
            "cracks",
            "crack",
            "splinters",
            "bursts",
            "falls apart",
            "розбивається",
            "розбиває",
            "розбив",
            "розбила",
            "розбилась",
            "розбилася",
            "розбилося",
            "розбилися",
            "розлітається",
            "розлетілась",
            "розлетілася",
            "розлетілося",
            "тріскає",
            "тріснуло",
            "тріснула",
            "трощить",
            "розтрощив",
            "лопнуло",
            "лопнула",
            "дзенькнуло",
            "розсипалось",
            "потрощив",
            "розлетівся",
            "розлетілись",
            "тріснув",
            "порепалося",
        ]),
        Term::negatives(&[
            "glass of",
            "through the window",
            "out the window",
            "looks through the glass",
            "келих вина",
            "келих з",
            "склянку води",
            "склянку вина",
            "через вікно",
            "у вікно",
            "крізь скло",
            "дивиться у вікно",
        ]),
    ]))
    .with_cooldown(3_000)
}

/// The generic magic event fires for anything the four specific ones do not. Those four
/// carry the words that name a *kind* of magic — a fireball, a heal, a teleport, a
/// freeze — and [`magic_cast`] lists them as negatives, so "кидає вогняну кулю" plays an
/// explosion rather than a generic shimmer on top of it.
fn fireball() -> EventDefinition {
    EventDefinition {
        category: "magic".to_string(),
        ..EventDefinition::new("FIREBALL", "Fireball")
    }
    .with_phrases(phrases(
        &[
            "casts fireball",
            "hurls a fireball",
            "the fireball explodes",
            "a ball of flame erupts in the corridor",
            "the blast throws you back",
            "the explosion tears through the room",
        ],
        &[
            "кидає вогняну кулю",
            "вогняна куля влучає в гоблінів",
            "вогняна куля вибухає",
            "фаєрбол розриває коридор",
            "лунає вибух",
            "вибухом його відкидає до стіни",
            "полум'яний вибух накриває загін",
        ],
        &["sound fireball", "sound explosion", "trigger fireball"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "fireball",
            "fire ball",
            "explosion",
            "blast",
            "detonation",
            "shockwave",
            // "вогняна куля" is two words; the phrase layer catches the pair, and the
            // adjective on its own is specific enough not to belong anywhere else.
            "вогняна",
            "вогняну",
            "вогняної",
            "вогняним",
            "фаєрбол",
            "фаєрбола",
            "фаєрболом",
            "файербол",
            "вибух",
            "вибуху",
            "вибухом",
            "вибухи",
            "детонація",
            "вогнекуля",
        ]),
        Term::actions(&[
            "casts",
            "hurls",
            "throws",
            "launches",
            "explodes",
            "explode",
            "exploded",
            "erupts",
            "detonates",
            "blasts",
            "tears through",
            "goes off",
            "кидає",
            "кинув",
            "кинула",
            "жбурляє",
            "жбурнув",
            "метає",
            "метнув",
            "запускає",
            "запустив",
            "вибухає",
            "вибухнув",
            "вибухнула",
            "вибухнуло",
            "вибухають",
            "розривається",
            "розірвався",
            "розриває",
            "розірвало",
            "рвонуло",
            "гримнуло",
            "лунає",
            "пролунав",
            "пролунало",
            "накриває",
            "накрив",
            "накрило",
            "влучає",
            "влучила",
            "влучив",
            "відкидає",
            "відкинуло",
        ]),
        Term::negatives(&[
            "fireball spell in your spellbook",
            "prepare fireball",
            "resistance to fire damage",
            "готує вогняну кулю на завтра",
            "вивчив вогняну кулю",
            "стійкість до вогню",
        ]),
    ]))
    .with_cooldown(3_000)
}

fn spell_heal() -> EventDefinition {
    EventDefinition {
        category: "magic".to_string(),
        ..EventDefinition::new("SPELL_HEAL", "Healing Magic")
    }
    .with_phrases(phrases(
        &[
            "heals your wounds",
            "casts cure wounds",
            "the wounds close over",
            "warm light knits the flesh together",
            "you are healed",
            "restores him to his feet",
        ],
        &[
            "зцілює твої рани",
            "лікує пораненого",
            "рани затягуються",
            "жрець накладає зцілення",
            "тепле світло загоює рану",
            "ти відновлюєш здоров'я",
            "піднімає його на ноги",
        ],
        &["sound heal", "sound healing", "trigger heal"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "heal",
            "heals",
            "healing",
            "cure",
            "cure wounds",
            "wounds",
            "wound",
            "restoration",
            "hit points",
            "зцілення",
            "зціленням",
            "лікування",
            "рана",
            "рани",
            "рану",
            "ран",
            "ранами",
            "поранення",
            "пораненого",
            "здоров'я",
            "хіти",
            "хітів",
            "цілитель",
            "цілителька",
            "знахар",
            "раною",
        ]),
        Term::actions(&[
            "heals",
            "heal",
            "healed",
            "cures",
            "cure",
            "cured",
            "restores",
            "restore",
            "restored",
            "mends",
            "knits",
            "closes",
            "close over",
            "зцілює",
            "зцілив",
            "зцілила",
            "зцілили",
            "зціляє",
            "лікує",
            "вилікував",
            "вилікувала",
            "полікував",
            "загоює",
            "загоїв",
            "загоїлася",
            "загоїлись",
            "затягуються",
            "затягнулася",
            "затягнулись",
            "відновлює",
            "відновив",
            "відновлюєш",
            "відновлюється",
            "піднімає на ноги",
            "оздоровлює",
            "накладає зцілення",
            "заживляє",
            "заживив",
            "заживила",
            "гоїть",
            "загоїли",
        ]),
        Term::negatives(&[
            "cannot be healed",
            "beyond healing",
            "no healing left",
            "не вдається зцілити",
            "зцілення не спрацювало",
            "не можна вилікувати",
        ]),
    ]))
    .with_cooldown(3_000)
}

fn spell_teleport() -> EventDefinition {
    EventDefinition {
        category: "magic".to_string(),
        ..EventDefinition::new("SPELL_TELEPORT", "Teleport")
    }
    .with_phrases(phrases(
        &[
            "teleports away",
            "vanishes in a puff of smoke",
            "steps through the portal",
            "blinks across the room",
            "a portal tears open in front of you",
            "disappears and reappears behind the guard",
        ],
        &[
            "телепортується геть",
            "зникає в клубі диму",
            "відкривається портал",
            "проходить крізь портал",
            "щезає і з'являється за спиною вартового",
            "стрибок переносить його на інший бік зали",
        ],
        &["sound teleport", "sound portal", "trigger teleport"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "teleport",
            "teleports",
            "portal",
            "portals",
            "gateway",
            "rift",
            "blink",
            "телепорт",
            "телепорту",
            "телепортом",
            "портал",
            "портала",
            "порталу",
            "порталом",
            "розлом",
            "розлому",
            "прохід",
            "проходу",
            "стрибок",
            "стрибка",
            "розломом",
            "стрибком",
        ]),
        Term::actions(&[
            "teleports",
            "teleport",
            "teleported",
            "vanishes",
            "vanish",
            "vanished",
            "disappears",
            "disappear",
            "reappears",
            "blinks",
            "steps through",
            "tears open",
            "opens",
            "телепортується",
            "телепортувався",
            "телепортував",
            "переноситься",
            "переносить",
            "переніс",
            "перенесло",
            "зникає",
            "зник",
            "зникла",
            "зникли",
            "щезає",
            "щез",
            "щезла",
            "розчиняється в повітрі",
            "з'являється",
            "з'явився",
            "з'явилася",
            "відкривається",
            "відкрився",
            "розкривається",
            "розкрився",
            "проходить крізь",
            "ступає крізь",
        ]),
        Term::negatives(&[
            "teleport is on cooldown",
            "the portal is closed",
            "no portal here",
            "портал закритий",
            "портал не працює",
            "телепорт недоступний",
        ]),
    ]))
    .with_cooldown(3_000)
}

fn spell_ice() -> EventDefinition {
    EventDefinition {
        category: "magic".to_string(),
        ..EventDefinition::new("SPELL_ICE", "Ice Magic")
    }
    .with_phrases(phrases(
        &[
            "casts ray of frost",
            "ice spreads across the floor",
            "freezes him where he stands",
            "a blast of cold tears through the hall",
            "the water turns to ice",
        ],
        &[
            "крижаний промінь влучає в орка",
            "лід укриває підлогу",
            "заморожує його на місці",
            "хвиля холоду накриває залу",
            "вода перетворюється на лід",
            "мороз сковує йому ноги",
        ],
        &["sound ice", "sound frost", "trigger ice"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "ice",
            "frost",
            "cold",
            "chill",
            "icicle",
            "blizzard",
            "лід",
            "льоду",
            "льодом",
            "крига",
            "кригою",
            "крижаний",
            "крижана",
            "крижаною",
            "крижаний промінь",
            "мороз",
            "морозу",
            "морозом",
            "холод",
            "холоду",
            "холодом",
            "паморозь",
            "бурулька",
            "заморозка",
        ]),
        Term::actions(&[
            "freezes",
            "freeze",
            "froze",
            "frozen",
            "chills",
            "spreads",
            "encases",
            "shatters into frost",
            "turns to ice",
            "заморожує",
            "заморозив",
            "заморозила",
            "замерзає",
            "замерз",
            "замерзла",
            "промерз",
            "укриває",
            "укрив",
            "вкрилася",
            "скує",
            "сковує",
            "скував",
            "скувало",
            "обпікає холодом",
            "перетворюється на лід",
            "тріскається від морозу",
            "накриває",
            "накрило",
            "влучає",
            "влучив",
        ]),
        Term::negatives(&[
            "resistance to cold",
            "immune to cold",
            "ice is thin here",
            "стійкість до холоду",
            "імунітет до холоду",
            "лід не тримає",
        ]),
    ]))
    .with_cooldown(3_000)
}

fn sword_unsheathe() -> EventDefinition {
    EventDefinition {
        category: "combat".to_string(),
        ..EventDefinition::new("SWORD_UNSHEATHE", "Drawing a Blade")
    }
    .with_phrases(phrases(
        &[
            "draws his sword",
            "pulls the blade from its scabbard",
            "unsheathes her dagger",
            "steel slides free of the scabbard",
            "draws steel",
        ],
        &[
            "витягує меч",
            "витягає меч із піхов",
            "оголює клинок",
            "дістає кинджал",
            "меч виходить із піхов зі скреготом",
            "хапається за руків'я і виймає зброю",
        ],
        &["sound draw sword", "trigger unsheathe"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "sword",
            "blade",
            "dagger",
            "steel",
            "scabbard",
            "sheath",
            "rapier",
            "меч",
            "меча",
            "мечем",
            "клинок",
            "клинка",
            "клинком",
            "кинджал",
            "кинджала",
            "кинджалом",
            "шабля",
            "шаблю",
            "шаблею",
            "піхви",
            "піхов",
            "піхвах",
            "зброю",
            "зброї",
            "руків'я",
            "зброєю",
        ]),
        Term::actions(&[
            "draws",
            "draw",
            "drew",
            "pulls",
            "unsheathes",
            "unsheathe",
            "unsheathed",
            "slides free",
            "bares",
            "витягує",
            "витягнув",
            "витягнула",
            "витягає",
            "витяг",
            "виймає",
            "вийняв",
            "вийняла",
            "дістає",
            "дістав",
            "дістала",
            "оголює",
            "оголив",
            "оголила",
            "висмикує",
            "висмикнув",
            "вихоплює",
            "вихопив",
            "вихопила",
            "хапається за руків'я",
            "виходить із піхов",
            "видобуває",
            "видобув",
        ]),
        Term::negatives(&[
            "sheathes his sword",
            "puts the sword away",
            "the sword stays in its scabbard",
            "ховає меч",
            "вкладає меч у піхви",
            "меч лишається в піхвах",
        ]),
    ]))
    .with_cooldown(3_000)
}

fn shield_block() -> EventDefinition {
    EventDefinition {
        category: "combat".to_string(),
        ..EventDefinition::new("SHIELD_BLOCK", "Blocks and Parries")
    }
    .with_phrases(phrases(
        &[
            "blocks the blow with his shield",
            "parries the strike",
            "the axe glances off the shield",
            "catches the blade on her buckler",
            "deflects the arrow",
        ],
        &[
            "блокує удар щитом",
            "парирує випад",
            "сокира зісковзує зі щита",
            "приймає удар на щит",
            "відбиває стрілу",
            "клинок дзвенить об щит",
        ],
        &["sound block", "sound parry", "trigger block"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "shield",
            "shields",
            "buckler",
            "block",
            "parry",
            "guard",
            "щит",
            "щита",
            "щитом",
            "щити",
            "щитів",
            "блок",
            "блоку",
            "блоком",
            "захист",
            "захисту",
            "удар",
            "удару",
            "ударом",
            "випад",
            "випаду",
            "щитами",
        ]),
        Term::actions(&[
            "blocks",
            "block",
            "blocked",
            "parries",
            "parry",
            "parried",
            "deflects",
            "deflect",
            "glances off",
            "catches",
            "turns aside",
            "блокує",
            "заблокував",
            "заблокувала",
            "парирує",
            "парирував",
            "відбиває",
            "відбив",
            "відбила",
            "відводить",
            "відвів",
            "приймає на щит",
            "прикривається",
            "прикрився",
            "затуляється",
            "затулився",
            "зісковзує",
            "зісковзнула",
            "зісковзнув",
            "дзвенить об щит",
            "відскакує",
            "відскочив",
            "підставляє",
            "підставив",
            "підставила",
            "виставляє",
            "виставив",
            "ловить на щит",
        ]),
        Term::negatives(&[
            "the shield is broken",
            "cannot block",
            "the blow gets through",
            "щит зламався",
            "не встигає заблокувати",
            "удар проходить",
        ]),
    ]))
    .with_cooldown(2_000)
}

fn armor_clank() -> EventDefinition {
    EventDefinition {
        category: "combat".to_string(),
        ..EventDefinition::new("ARMOR_CLANK", "Armour")
    }
    .with_phrases(phrases(
        &[
            "the guard's armour clanks as he turns",
            "chainmail rattles in the dark",
            "buckles on his plate",
            "steel plates grind against each other",
        ],
        &[
            "обладунки брязкають при кожному кроці",
            "кольчуга дзвенить у темряві",
            "лати скрегочуть",
            "вартовий поправляє обладунки",
            "броня гримить",
        ],
        &["sound armor", "trigger armour"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "armour",
            "armor",
            "chainmail",
            "chain mail",
            "plate",
            "plates",
            "breastplate",
            "gauntlet",
            "helm",
            "обладунки",
            "обладунків",
            "обладунками",
            "кольчуга",
            "кольчугу",
            "кольчуги",
            "лати",
            "латах",
            "латами",
            "броня",
            "броню",
            "бронею",
            "панцир",
            "панцира",
            "наплічники",
            "шолом",
            "шолома",
            "шоломом",
            "нагрудник",
            "кольчузі",
            "нагрудника",
        ]),
        Term::actions(&[
            "clanks",
            "clank",
            "clanked",
            "rattles",
            "rattle",
            "rattled",
            "clatters",
            "jangles",
            "grinds",
            "creaks",
            "buckles",
            "брязкають",
            "брязкає",
            "брязнули",
            "брязнув",
            "дзвенить",
            "дзвенять",
            "задзвеніли",
            "гримить",
            "гримлять",
            "загриміли",
            "скрегочуть",
            "скрегоче",
            "заскреготіли",
            "торохтять",
            "торохтить",
            "деренчить",
            "поправляє",
            "поправив",
            "одягає",
            "одягнув",
            "застібає",
            "застібнув",
        ]),
        Term::negatives(&[
            "the armour lies in the corner",
            "takes off his armour",
            "обладунки лежать у кутку",
            "знімає обладунки",
        ]),
    ]))
    .with_cooldown(4_000)
}

fn body_fall() -> EventDefinition {
    EventDefinition {
        category: "combat".to_string(),
        ..EventDefinition::new("BODY_FALL", "A Body Hits the Ground")
    }
    .with_phrases(phrases(
        &[
            "the goblin drops dead",
            "the body hits the floor",
            "collapses in a heap",
            "falls lifeless to the stones",
            "the guard crumples where he stands",
        ],
        &[
            "гоблін падає замертво",
            "тіло гупає об підлогу",
            "звалюється на каміння",
            "вартовий осідає на землю",
            "падає мертвим до твоїх ніг",
            "труп важко гепається додолу",
        ],
        &["sound body fall", "trigger body"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "body",
            "corpse",
            "dead",
            "lifeless",
            "floor",
            "ground",
            "тіло",
            "тіла",
            "тілом",
            "труп",
            "трупа",
            "трупом",
            "мертвий",
            "мертвим",
            "замертво",
            "непритомний",
            "підлогу",
            "підлозі",
            "землю",
            "землі",
            "додолу",
            "каміння",
        ]),
        Term::actions(&[
            "drops dead",
            "falls",
            "fall",
            "fell",
            "collapses",
            "collapse",
            "crumples",
            "hits the floor",
            "slumps",
            "topples",
            "падає",
            "впав",
            "впала",
            "впало",
            "падають",
            "звалюється",
            "звалився",
            "звалилася",
            "гупає",
            "гупнув",
            "гупнуло",
            "гепається",
            "гепнувся",
            "гепнулося",
            "осідає",
            "осів",
            "осіла",
            "валиться",
            "повалився",
            "повалилася",
            "гримнувся",
            "розпластався",
            "обм'якає",
            "обм'як",
        ]),
        Term::negatives(&[
            "gets back up",
            "still standing",
            "the body is already there",
            "підводиться",
            "встає на ноги",
            "тіло вже лежало тут",
        ]),
    ]))
    .with_cooldown(2_000)
}

fn scream() -> EventDefinition {
    EventDefinition {
        category: "combat".to_string(),
        ..EventDefinition::new("SCREAM", "Screams")
    }
    .with_phrases(phrases(
        &[
            "screams in pain",
            "a scream echoes down the corridor",
            "shrieks and falls back",
            "cries out as the blade bites",
            "you hear a scream from the next room",
        ],
        &[
            "кричить від болю",
            "крик лунає коридором",
            "верещить і відсахується",
            "скрикує від удару",
            "з сусідньої кімнати чути крик",
            "зойк розриває тишу",
        ],
        &["sound scream", "trigger scream"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "scream",
            "screams",
            "shriek",
            "shrieks",
            "cry",
            "wail",
            "yell",
            "крик",
            "крику",
            "криком",
            "зойк",
            "зойку",
            "вереск",
            "вереску",
            "лемент",
            "лементу",
            "виск",
            "болю",
            "біль",
            // A scream is one of the few events whose verb *is* the object. The gate
            // needs a keyword as well as an action, and "Вона заверещала і відсахнулася"
            // has no noun to offer it.
            "кричить",
            "закричав",
            "закричала",
            "верещить",
            "заверещав",
            "заверещала",
            "зойкнув",
            "зойкнула",
            "screams",
            "screamed",
            "shrieks",
            "shrieked",
            "заволав",
            "заволала",
            "волає",
            "зойкає",
            "лементує",
            "болем",
        ]),
        Term::actions(&[
            "screams",
            "scream",
            "screamed",
            "screaming",
            "shrieks",
            "shrieked",
            "cries out",
            "yells",
            "wails",
            "echoes",
            "кричить",
            "закричав",
            "закричала",
            "кричать",
            "заволав",
            "волає",
            "верещить",
            "заверещав",
            "заверещала",
            "скрикує",
            "скрикнув",
            "скрикнула",
            "зойкає",
            "зойкнув",
            "зойкнула",
            "лементує",
            "залементував",
            "лунає",
            "пролунав",
            "розриває тишу",
            "чути",
        ]),
        Term::negatives(&[
            "silent scream",
            "nobody screams",
            "no one cries out",
            "ніхто не кричить",
            "мовчки",
            "тиша",
        ]),
    ]))
    .with_cooldown(3_500)
}

fn dragon_roar() -> EventDefinition {
    EventDefinition {
        category: "creatures".to_string(),
        ..EventDefinition::new("DRAGON_ROAR", "Dragons")
    }
    .with_phrases(phrases(
        &[
            "the dragon roars",
            "a roar shakes the cavern",
            "the wyrm bellows above you",
            "the beast lets out a deafening roar",
            "the dragon rears up and roars",
        ],
        &[
            "дракон реве",
            "рев дракона трясе печеру",
            "чудовисько ричить над вами",
            "дракон розправляє крила і реве",
            "звір видає оглушливий рик",
        ],
        &["sound dragon", "sound roar", "trigger dragon"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "dragon",
            "dragons",
            "wyrm",
            "wyvern",
            "drake",
            "beast",
            "monster",
            "дракон",
            "дракона",
            "драконом",
            "дракони",
            "драконів",
            "змій",
            "змія",
            "виверна",
            "виверни",
            "чудовисько",
            "чудовиська",
            "чудовиськом",
            "звір",
            "звіра",
            "звіром",
            "монстр",
            "монстра",
            "рев",
            "реву",
            "рик",
            "рику",
            "змієм",
            "ревом",
            "риком",
        ]),
        Term::actions(&[
            "roars",
            "roar",
            "roared",
            "bellows",
            "bellow",
            "howls",
            "shrieks",
            "shakes",
            "lets out",
            "rears up",
            "реве",
            "заревів",
            "заревіла",
            "ревіння",
            "ричить",
            "заричав",
            "заричала",
            "рикає",
            "рикнув",
            "гарчить",
            "загарчав",
            "гуркоче",
            "трясе",
            "струшує",
            "здригнулася",
            "видає",
            "видав",
            "розправляє крила",
            "лунає",
            "пролунав",
        ]),
        Term::negatives(&[
            "the dragon is asleep",
            "a painting of a dragon",
            "dragon statue",
            "дракон спить",
            "статуя дракона",
            "малюнок дракона",
        ]),
    ]))
    .with_cooldown(6_000)
}

fn horse() -> EventDefinition {
    EventDefinition {
        category: "creatures".to_string(),
        ..EventDefinition::new("HORSE", "Horses")
    }
    .with_phrases(phrases(
        &[
            "the horse whinnies",
            "hooves clatter on the cobbles",
            "riders gallop down the road",
            "the mare rears and neighs",
            "you hear horses approaching",
        ],
        &[
            "кінь ірже",
            "копита стукотять по бруківці",
            "вершники мчать дорогою",
            "кобила стає дибки й ірже",
            "чути, як наближаються коні",
            "карета під'їжджає до брами",
        ],
        &["sound horse", "trigger horse"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "horse",
            "horses",
            "mare",
            "stallion",
            "pony",
            "hooves",
            "hoof",
            "steed",
            "rider",
            "riders",
            "cart",
            "carriage",
            "кінь",
            "коня",
            "конем",
            "коні",
            "коней",
            "кобила",
            "кобилу",
            "жеребець",
            "жеребця",
            "копита",
            "копитами",
            "вершник",
            "вершника",
            "вершники",
            "карета",
            "карету",
            "віз",
            "воза",
            "кіньми",
            "возом",
        ]),
        Term::actions(&[
            "whinnies",
            "neighs",
            "neigh",
            "gallops",
            "gallop",
            "canters",
            "clatter",
            "clatters",
            "rears",
            "approaching",
            "ірже",
            "заіржав",
            "заіржала",
            "ірження",
            "чвалує",
            "мчить",
            "мчать",
            "помчав",
            "скаче",
            "скачуть",
            "поскакав",
            "галопом",
            "стукотять",
            "стукотіли",
            "цокотять",
            "цокають",
            "тупотять",
            "наближаються",
            "зацокотіли",
            "зацокотів",
            "застукотіли",
            "затупотіли",
            "загупали",
            "наближається",
            "під'їжджає",
            "під'їхала",
            "стає дибки",
        ]),
        Term::negatives(&[
            "the horse is dead",
            "wooden horse",
            "horse statue",
            "кінь мертвий",
            "дерев'яний кінь",
            "статуя коня",
        ]),
    ]))
    .with_cooldown(4_000)
}

fn ghost_moan() -> EventDefinition {
    EventDefinition {
        category: "creatures".to_string(),
        ..EventDefinition::new("GHOST_MOAN", "Ghosts and Spirits")
    }
    .with_phrases(phrases(
        &[
            "a ghost drifts through the wall",
            "a spirit moans in the dark",
            "the wraith wails",
            "cold whispers fill the chapel",
            "the spectre appears before you",
        ],
        &[
            "привид пропливає крізь стіну",
            "дух стогне в темряві",
            "примара завиває",
            "холодний шепіт заповнює каплицю",
            "постає привид",
            "нежить стогне десь попереду",
        ],
        &["sound ghost", "trigger ghost"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "ghost",
            "ghosts",
            "spirit",
            "spirits",
            "wraith",
            "spectre",
            "specter",
            "phantom",
            "poltergeist",
            "banshee",
            "привид",
            "привида",
            "привидом",
            "привиди",
            "дух",
            "духа",
            "духом",
            "духи",
            "примара",
            "примари",
            "примарою",
            "мара",
            "нежить",
            "нежиті",
            "шепіт",
            "шепоту",
            "стогін",
            "стогону",
            "духів",
            "марою",
        ]),
        Term::actions(&[
            "moans",
            "moan",
            "wails",
            "wail",
            "whispers",
            "drifts",
            "floats",
            "appears",
            "materialises",
            "haunts",
            "стогне",
            "застогнав",
            "застогнала",
            "стогнуть",
            "завиває",
            "завив",
            "завила",
            "виє",
            "шепоче",
            "зашепотів",
            "шепочуть",
            "пропливає",
            "проплив",
            "пролітає",
            "ширяє",
            "з'являється",
            "з'явився",
            "постає",
            "постав",
            "матеріалізується",
            "заповнює",
        ]),
        Term::negatives(&[
            "there are no ghosts here",
            "a story about a ghost",
            "тут немає привидів",
            "легенда про привида",
            "розповідь про духів",
        ]),
    ]))
    .with_cooldown(5_000)
}

fn bones() -> EventDefinition {
    EventDefinition {
        category: "creatures".to_string(),
        ..EventDefinition::new("BONES", "Bones and Skeletons")
    }
    .with_phrases(phrases(
        &[
            "the skeleton rises, bones rattling",
            "bones crunch underfoot",
            "a pile of bones shifts",
            "the skull cracks",
            "skeletal fingers scrape the stone",
        ],
        &[
            "скелет підіймається, брязкаючи кістками",
            "кістки хрустять під ногами",
            "купа кісток осипається",
            "череп тріскається",
            "кістяні пальці шкребуть камінь",
            "кістяк вилазить із могили",
        ],
        &["sound bones", "sound skeleton", "trigger bones"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "bone",
            "bones",
            "skeleton",
            "skeletons",
            "skeletal",
            "skull",
            "skulls",
            "ribcage",
            "кістка",
            "кістки",
            "кісток",
            "кістками",
            "кістяк",
            "кістяка",
            "кістяні",
            "скелет",
            "скелета",
            "скелетом",
            "скелети",
            "череп",
            "черепа",
            "черепом",
            "черепи",
            "могили",
            "могилу",
            "кістці",
        ]),
        Term::actions(&[
            "rattles",
            "rattle",
            "rattling",
            "crunch",
            "crunches",
            "cracks",
            "crack",
            "shifts",
            "scrape",
            "scrapes",
            "rises",
            "clatter",
            "брязкають",
            "брязкаючи",
            "брязнули",
            "хрустять",
            "хруснули",
            "хрустить",
            "тріщать",
            "тріскається",
            "тріснув",
            "розсипаються",
            "розсипалися",
            "осипається",
            "осипалася",
            "шкребуть",
            "шкребе",
            "підіймається",
            "підіймаються",
            "піднявся",
            "встає",
            "вилазить",
            "виліз",
            "стукотять",
        ]),
        Term::negatives(&[
            "a bone he keeps as a trophy",
            "bones in the soup",
            "кістка на трофей",
            "кістки в супі",
        ]),
    ]))
    .with_cooldown(3_500)
}

fn crow() -> EventDefinition {
    EventDefinition {
        category: "creatures".to_string(),
        ..EventDefinition::new("CROW", "Crows and Ravens")
    }
    .with_phrases(phrases(
        &[
            "crows caw from the gallows",
            "a raven croaks overhead",
            "birds scatter from the trees",
            "the flock takes off in alarm",
        ],
        &[
            "ворони каркають над шибеницею",
            "крук каркає згори",
            "птахи зриваються з дерев",
            "зграя злітає з галасом",
            "вороння кружляє над полем",
        ],
        &["sound crows", "sound birds", "trigger crow"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "crow",
            "crows",
            "raven",
            "ravens",
            "rook",
            "bird",
            "birds",
            "flock",
            "ворон",
            "ворона",
            "ворони",
            "воронів",
            "вороння",
            "крук",
            "крука",
            "круки",
            "птах",
            "птаха",
            "птахи",
            "птахів",
            "зграя",
            "зграю",
            "шибениця",
            "шибеницею",
            "зграєю",
        ]),
        Term::actions(&[
            "caw",
            "caws",
            "cawing",
            "croaks",
            "croak",
            "scatter",
            "scatters",
            "takes off",
            "circle",
            "circles",
            "каркають",
            "каркає",
            "закаркали",
            "закаркав",
            "кряче",
            "крячуть",
            "зриваються",
            "зірвалися",
            "злітає",
            "злітають",
            "злетіли",
            "здіймаються",
            "кружляє",
            "кружляють",
            "кружляло",
            "закружляли",
            "закружляв",
            "закружляла",
            "розсілися",
            "галасують",
            "розлітаються",
            "розлетілися",
        ]),
        Term::negatives(&[
            "a stuffed raven",
            "the crow on the sign",
            "опудало ворона",
            "ворон на вивісці",
        ]),
    ]))
    .with_cooldown(5_000)
}

fn potion_drink() -> EventDefinition {
    EventDefinition {
        category: "items".to_string(),
        ..EventDefinition::new("POTION_DRINK", "Drinking a Potion")
    }
    .with_phrases(phrases(
        &[
            "drinks the potion",
            "downs the healing draught in one gulp",
            "uncorks the vial and drinks",
            "swallows the elixir",
            "takes a long drink from the flask",
        ],
        &[
            "випиває зілля",
            "залпом випиває флакон",
            "відкорковує пляшечку і п'є",
            "ковтає еліксир",
            "робить довгий ковток із фляги",
            "п'є настоянку",
        ],
        &["sound potion", "sound drink", "trigger potion"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "potion",
            "potions",
            "elixir",
            "draught",
            "vial",
            "flask",
            "philtre",
            "зілля",
            "зіллям",
            "еліксир",
            "еліксира",
            "еліксиром",
            "флакон",
            "флакона",
            "флаконом",
            "пляшечка",
            "пляшечку",
            "фляга",
            "флягу",
            "флягою",
            "настоянка",
            "настоянку",
            "мікстура",
            "мікстуру",
            "пляшечкою",
            "флязі",
        ]),
        Term::actions(&[
            "drinks",
            "drink",
            "drank",
            "downs",
            "swallows",
            "swallow",
            "gulps",
            "sips",
            "uncorks",
            "quaffs",
            "випиває",
            "випив",
            "випила",
            "п'є",
            "попив",
            "ковтає",
            "ковтнув",
            "ковтнула",
            "проковтнув",
            "перехиляє",
            "перехилив",
            "відкорковує",
            "відкоркував",
            "відкриває флакон",
            "робить ковток",
            "хлебче",
            "хлебнув",
            "осушує",
            "осушив",
        ]),
        Term::negatives(&[
            "the potion is empty",
            "puts the potion in his pack",
            "buys a potion",
            "флакон порожній",
            "ховає зілля в сумку",
            "купує зілля",
            // A flask is not always a potion, and someone taking a drink of water at
            // camp is not an event.
            "drinks water",
            "water from the flask",
            "п'є воду",
            "п'ють воду",
            "напився води",
        ]),
    ]))
    .with_cooldown(3_000)
}

fn dice_roll() -> EventDefinition {
    EventDefinition {
        category: "items".to_string(),
        ..EventDefinition::new("DICE_ROLL", "Dice")
    }
    .with_phrases(phrases(
        &[
            "roll a d20",
            "make a perception check",
            "roll for initiative",
            "give me a saving throw",
            "roll damage",
        ],
        &[
            "кидай д20",
            "кидай кубик",
            "перевірка на сприйняття",
            "кидаємо ініціативу",
            "зроби рятівний кидок",
            "кидай на шкоду",
        ],
        &["sound dice", "trigger dice"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "dice",
            "die",
            "d20",
            "d12",
            "d10",
            "d8",
            "d6",
            "d4",
            "initiative",
            "check",
            "saving throw",
            "кубик",
            "кубика",
            "кубиком",
            "кубики",
            "кості",
            "кісток",
            "д20",
            "д12",
            "д10",
            "д8",
            "д6",
            "д4",
            "ініціатива",
            "ініціативу",
            "перевірка",
            "перевірку",
            "кидок",
            "кидка",
            "перевірці",
        ]),
        Term::actions(&[
            "roll",
            "rolls",
            "rolled",
            "rolling",
            "throw",
            "throws",
            "make",
            "give me",
            "кидай",
            "кидайте",
            "кидає",
            "кинув",
            "кинула",
            "кидаємо",
            "кидаю",
            "покидай",
            "перекидай",
            "зроби",
            "зробіть",
            "робимо",
            "викидає",
            "викинув",
        ]),
        Term::negatives(&[
            "no roll needed",
            "you do not have to roll",
            "кидати не треба",
            "без кидка",
            "автоматичний успіх",
        ]),
    ]))
    .with_cooldown(2_000)
}

fn keys_lock() -> EventDefinition {
    EventDefinition {
        category: "items".to_string(),
        ..EventDefinition::new("KEYS_LOCK", "Keys and Locks")
    }
    .with_phrases(phrases(
        &[
            "turns the key in the lock",
            "keys jingle on his belt",
            "picks the lock",
            "the lock clicks open",
            "fumbles with the padlock",
        ],
        &[
            "повертає ключ у замку",
            "ключі дзвенять на поясі",
            "зламує замок відмичкою",
            "замок клацає",
            "порпається з колодкою",
            "відмикає замок",
        ],
        &["sound keys", "sound lock", "trigger lock"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "key",
            "keys",
            "lock",
            "locks",
            "padlock",
            "keyhole",
            "lockpick",
            "lockpicks",
            "ключ",
            "ключа",
            "ключем",
            "ключі",
            "ключів",
            "замок",
            "замка",
            "замком",
            "замки",
            "колодка",
            "колодку",
            "відмичка",
            "відмичку",
            "відмичкою",
            "щілина",
            "шпарина",
            "колодці",
            "колодкою",
        ]),
        Term::actions(&[
            "turns",
            "turn",
            "turned",
            "unlocks",
            "unlock",
            "locks",
            "picks",
            "picking",
            "jingle",
            "jingles",
            "clicks",
            "rattles",
            "fumbles",
            "повертає",
            "повернув",
            "повернула",
            "відмикає",
            "відімкнув",
            "відімкнула",
            "замикає",
            "замкнув",
            "зачиняє на замок",
            "зламує",
            "зламав",
            "відкриває відмичкою",
            "клацає",
            "клацнув",
            "клацнуло",
            "дзвенять",
            "дзвенить",
            "задзвеніли",
            "брязкають",
            "порпається",
            "колупається",
        ]),
        Term::negatives(&[
            "the key is lost",
            "there is no lock",
            "ключ загублений",
            "замка немає",
            "без ключа",
            // A lock that stays shut makes no sound. "locked" and "замкнені" are the
            // state, not the act, and the state is what a stuck door gets described in.
            "is locked",
            "was locked",
            "stays locked",
            "will not budge",
            "замкнено",
            "замкнені",
            "зачинено на замок",
            "не піддаються",
        ]),
    ]))
    .with_cooldown(2_500)
}

fn scroll_paper() -> EventDefinition {
    EventDefinition {
        category: "items".to_string(),
        ..EventDefinition::new("SCROLL_PAPER", "Scrolls and Maps")
    }
    .with_phrases(phrases(
        &[
            "unrolls the map on the table",
            "unfurls the scroll",
            "turns the page",
            "the parchment crackles as it opens",
            "leafs through the tome",
        ],
        &[
            "розгортає карту на столі",
            "розгортає сувій",
            "гортає сторінку",
            "пергамент шурхотить",
            "гортає фоліант",
            "розкриває манускрипт",
        ],
        &["sound scroll", "sound paper", "trigger scroll"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "scroll",
            "scrolls",
            "map",
            "maps",
            "parchment",
            "page",
            "pages",
            "letter",
            "book",
            "tome",
            "paper",
            "сувій",
            "сувоя",
            "сувоєм",
            "сувої",
            "карта",
            "карту",
            "картою",
            "пергамент",
            "пергаменту",
            "сторінка",
            "сторінку",
            "сторінки",
            "лист",
            "листа",
            "книга",
            "книгу",
            "фоліант",
            "манускрипт",
            "папір",
            "паперу",
            "сторінці",
            "книзі",
        ]),
        Term::actions(&[
            "unrolls",
            "unroll",
            "unfurls",
            "unfolds",
            "opens",
            "turns",
            "leafs",
            "flips",
            "crackles",
            "rustles",
            "розгортає",
            "розгорнув",
            "розгорнула",
            "розкриває",
            "розкрив",
            "розкрила",
            "розкладає",
            "розклав",
            "гортає",
            "перегортає",
            "перегорнув",
            "гортаючи",
            "шурхотить",
            "зашурхотів",
            "шелестить",
            "зашелестів",
            "згортає",
            "згорнув",
            "читає з сувою",
        ]),
        Term::negatives(&[
            "the scroll is blank",
            "the map is useless",
            "сувій порожній",
            "карта нічого не дає",
        ]),
    ]))
    .with_cooldown(3_000)
}

/// Wind deliberately does not list `буря`, `гроза` or `storm`: [`thunder`] owns those,
/// and a storm described in one sentence must not play two weather sounds at once.
fn wind() -> EventDefinition {
    EventDefinition {
        category: "weather".to_string(),
        ..EventDefinition::new("WIND", "Wind")
    }
    .with_phrases(phrases(
        &[
            "the wind howls through the pass",
            "a cold wind cuts across the moor",
            "wind whistles through the broken window",
            "a gust slams into you",
        ],
        &[
            "вітер виє в ущелині",
            "холодний вітер шмагає по обличчю",
            "вітер свище крізь розбите вікно",
            "порив вітру збиває з ніг",
            "протяг гуляє коридором",
        ],
        &["sound wind", "trigger wind"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "wind",
            "winds",
            "gust",
            "gusts",
            "gale",
            "breeze",
            "draught",
            "blizzard",
            "вітер",
            "вітру",
            "вітром",
            "вітри",
            "порив",
            "пориву",
            "поривом",
            "протяг",
            "протягу",
            "завірюха",
            "завірюху",
            "хуртовина",
            "хуртовину",
            "хурделиця",
            "протяги",
        ]),
        Term::actions(&[
            "howls",
            "howl",
            "whistles",
            "whistle",
            "whips",
            "cuts",
            "blows",
            "blow",
            "gusts",
            "slams into",
            "tears at",
            "виє",
            "завив",
            "завила",
            "завиває",
            "свище",
            "засвистів",
            "свистить",
            "шмагає",
            "шмагнув",
            "б'є в обличчя",
            "гуляє",
            "гуде",
            "загуло",
            "задуває",
            "задув",
            "дме",
            "подув",
            "повіяв",
            "повіяло",
            "збиває з ніг",
            "рве",
            "шарпає",
            "налітає",
            "налетів",
        ]),
        Term::negatives(&[
            "windless",
            "not a breath of wind",
            "the wind died down",
            "ані вітерцю",
            "вітер стих",
            "безвітряно",
        ]),
    ]))
    .with_cooldown(8_000)
}

fn rain() -> EventDefinition {
    EventDefinition {
        category: "weather".to_string(),
        ..EventDefinition::new("RAIN", "Rain")
    }
    .with_phrases(phrases(
        &[
            "it begins to rain",
            "rain hammers on the roof",
            "the downpour soaks you through",
            "drizzle turns to a steady rain",
        ],
        &[
            "починається дощ",
            "дощ тарабанить по даху",
            "злива промочує вас до нитки",
            "мряка переходить у дощ",
            "краплі стукають по бруківці",
        ],
        &["sound rain", "trigger rain"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "rain",
            "rains",
            "downpour",
            "drizzle",
            "shower",
            "raindrops",
            "дощ",
            "дощу",
            "дощем",
            "злива",
            "зливу",
            "зливою",
            "мряка",
            "мряку",
            "мжичка",
            "краплі",
            "крапель",
            "краплями",
            "калюжі",
        ]),
        Term::actions(&[
            "rains",
            "raining",
            "begins to rain",
            "hammers",
            "pours",
            "pouring",
            "drums",
            "patters",
            "soaks",
            "falls",
            "починається",
            "почався",
            "почалася",
            "ллє",
            "полив",
            "полило",
            "накрапає",
            "накрапало",
            "тарабанить",
            "затарабанив",
            "барабанить",
            "стукають",
            "стукотять",
            "періщить",
            "заперіщив",
            "мжичить",
            "мжичило",
            "промочує",
            "промочив",
            "промокли",
            "заливає",
            "залило",
            "сіється",
        ]),
        Term::negatives(&[
            "the rain has stopped",
            "no rain today",
            "дощ припинився",
            "дощу немає",
            "після дощу",
        ]),
    ]))
    .with_cooldown(8_000)
}

fn bell() -> EventDefinition {
    EventDefinition {
        category: "environment".to_string(),
        ..EventDefinition::new("BELL", "Bells")
    }
    .with_phrases(phrases(
        &[
            "the temple bell tolls",
            "bells ring out over the city",
            "the alarm bell sounds",
            "a bell chimes midnight",
        ],
        &[
            "дзвін б'є на храмі",
            "дзвони гудуть над містом",
            "б'є на сполох",
            "дзвін вибиває опівніч",
            "лунає удар дзвону",
        ],
        &["sound bell", "trigger bell"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "bell",
            "bells",
            "chime",
            "chimes",
            "toll",
            "belfry",
            "дзвін",
            "дзвону",
            "дзвоном",
            "дзвони",
            "дзвонів",
            "дзвіниця",
            "дзвіницю",
            "сполох",
            "сполоху",
            "набат",
            "набату",
            "куранти",
        ]),
        Term::actions(&[
            "tolls",
            "toll",
            "tolled",
            "rings",
            "ring",
            "rang",
            "chimes",
            "chime",
            "sounds",
            "peals",
            "strikes",
            "б'є",
            "вдарив",
            "ударив",
            "б'ють",
            "забив",
            "гудуть",
            "гуде",
            "загув",
            "загули",
            "дзвонить",
            "задзвонив",
            "задзвонили",
            "дзвенить",
            "задзвенів",
            "вибиває",
            "вибив",
            "лунає",
            "пролунав",
            "розноситься",
            "рознісся",
        ]),
        Term::negatives(&[
            "the bell is silent",
            "the bell rope is cut",
            "дзвін мовчить",
            "мотузку від дзвона зрізано",
        ]),
    ]))
    .with_cooldown(6_000)
}

fn tavern() -> EventDefinition {
    EventDefinition {
        category: "environment".to_string(),
        ..EventDefinition::new("TAVERN", "Tavern")
    }
    .with_phrases(phrases(
        &[
            "you push into the crowded tavern",
            "the inn is loud with talk and laughter",
            "mugs bang on the tables",
            "the common room falls into a hum of voices",
        ],
        &[
            "ви заходите в переповнену таверну",
            "у корчмі гамірно від розмов і сміху",
            "кухлі гупають об столи",
            "загальна зала гуде голосами",
            "шинок повний людей",
        ],
        &["sound tavern", "trigger tavern"],
    ))
    .with_terms(terms([
        Term::keywords(&[
            "tavern",
            "taverns",
            "inn",
            "alehouse",
            "common room",
            "innkeeper",
            "barkeep",
            "mug",
            "mugs",
            "tankard",
            "таверна",
            "таверну",
            "таверні",
            "корчма",
            "корчму",
            "корчмі",
            "шинок",
            "шинку",
            "заїзд",
            "заїзді",
            "трактир",
            "трактирі",
            "кухоль",
            "кухлі",
            "кухлів",
            "шинкар",
            "шинкаря",
            "корчмар",
            "корчмаря",
        ]),
        Term::actions(&[
            "enter",
            "enters",
            "push into",
            "step into",
            "walk into",
            "is loud",
            "hums",
            "bang",
            "bangs",
            "laughs",
            "заходите",
            "заходить",
            "зайшли",
            "зайшов",
            "заходять",
            "входите",
            "увійшли",
            "ступаєте",
            "гамірно",
            "гуде",
            "гудуть",
            "загуло",
            "шумить",
            "гупають",
            "гупнули",
            "сміються",
            "регочуть",
            "галасують",
            "повний людей",
        ]),
        Term::negatives(&[
            "the tavern is empty",
            "the inn is closed",
            "leaves the tavern",
            "таверна порожня",
            "корчма зачинена",
            "виходить із таверни",
        ]),
    ]))
    .with_cooldown(10_000)
}
#[cfg(test)]
mod tests {
    use super::*;
    use crate::event::EventKind;
    use std::collections::HashSet;

    #[test]
    fn the_seed_set_covers_the_events_the_spec_asks_for() {
        let ids: HashSet<String> = seed_events().into_iter().map(|e| e.id).collect();

        for expected in [
            "OPEN_DOOR",
            "DOOR_SLAM",
            "CHEST_OPEN",
            "SWORD_SWING",
            "BOW_SHOT",
            "THUNDER",
            "FIRE",
            "WATER_SPLASH",
            "WOLF_GROWL",
            "SMALL_CREATURE_SCURRY",
            "FOOTSTEPS",
            "MAGIC_CAST",
            "COINS",
            "GLASS_SHATTER",
        ] {
            assert!(ids.contains(expected), "missing {expected}");
        }
    }

    #[test]
    fn every_seed_event_is_usable_as_shipped() {
        for event in seed_events() {
            assert!(!event.id.is_empty());
            assert!(!event.display_name.is_empty());
            assert!(!event.category.is_empty(), "{} has no category", event.id);
            assert!(event.enabled);
            assert_eq!(event.kind, EventKind::OneShot);

            assert!(
                event.examples().count() >= 4,
                "{} needs enough phrasings to be useful",
                event.id
            );
            assert!(
                event.commands().count() >= 1,
                "{} should have a spoken command",
                event.id
            );
            assert!(
                (0.75..=0.95).contains(&event.confidence_threshold),
                "{} has an implausible threshold",
                event.id
            );
            assert!(
                event.cooldown_ms >= 1_000,
                "{} would retrigger too fast",
                event.id
            );
        }
    }

    #[test]
    fn every_seed_event_has_phrases_in_both_languages() {
        for event in seed_events() {
            let languages: HashSet<Lang> = event.examples().map(|phrase| phrase.lang).collect();
            assert!(
                languages.contains(&Lang::En) && languages.contains(&Lang::Uk),
                "{} is missing a language",
                event.id
            );
        }
    }

    #[test]
    fn events_that_can_be_described_without_happening_have_action_words() {
        // A sword can lie on a table; thunder cannot lie on a table. Anything whose
        // object can be mentioned passively needs the action gate.
        for event in seed_events() {
            if event.require_action_word {
                assert!(
                    event.terms_of(crate::event::TermKind::Action).count() >= 3,
                    "{} gates on action words but barely lists any",
                    event.id
                );
            }
        }
    }
}
